site_name: 'Kitupiikin käsikirja'
site_description: 'Avoimen lähdekoodin kirjanpitäjä'
site_author: 'Arto Hyvättinen'
site_url: 'https://artoh.github.io/kitupiikki'

# repo_name: 'GitHub'
# repo_url: 'https://github.com/artoh/kitupiikki'

copyright: 'Copyright &copy; 2017-2018 Arto Hyvättinen GPL3 License'
theme_dir: 'material'
extra:
  logo: 'images/Possu64.png'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  social:
    - type: 'github'
      link: 'https://github.com/artoh/kitupiikki'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCVNHCMQoNb66OgzuTSfdKqQ'
markdown_extensions:
  - admonition
  - footnotes
  - meta
pages:
  - Kitupiikki: 'index.md'
  - Kirjanpidosta lyhyesti: 'kirjanpito/kirjanpito.md'
  - Asennus: 'asennus.md'
  - Kirjanpidon aloittaminen: 'aloitus/aloitus.md'
  - Määritykset (vanha): 'maaritykset.md'
  - Määritykset:
    - Perusvalinnat: 'maaritykset/perusvalinnat/perusvalinnat.md'
  - Kirjaaminen: 'kirjaus.md'
  - Selaaminen ja etsiminen: 'selaus.md'
  - Tulosteet: 'raportti.md'
  - Tilinpäätös: 'tilinpaatos.md'
  - Sähköinen arkisto: 'arkisto.md'
  - Laskutus: 'laskutus.md'
  - Arvonlisävero: 'alv.md'
  - Muita toimintoja: 'muut.md'
  - Lisenssi: 'lisenssi.md'
google_analytics:
  - 'UA-92837430-1'
  - 'auto'
extra_css:
  - 'stylesheets/extra.css'
