site_name: 'Kitupiikin käsikirja'
site_description: 'Avoimen lähdekoodin kirjanpitäjä'
site_author: 'Arto Hyvättinen'
site_url: 'https://artoh.github.io/kitupiikki'

# repo_name: 'GitHub'
# repo_url: 'https://github.com/artoh/kitupiikki'

copyright: 'Copyright &copy; 2017-2018 Arto Hyvättinen GPL3 License'
theme:
  name: null
  custom_dir: material
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  logo: 'images/Possu64.png'
  language: 'fi'
  favicon: 'images/Possu64.png'
  font: 'Sans'
  code: 'Mono'
  feature:
    tabs: false
extra:
  disqus: 'Kitupiikki'
  social:
    - type: 'github'
      link: 'https://github.com/artoh/kitupiikki'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCVNHCMQoNb66OgzuTSfdKqQ'
  search:
    language: 'fi'
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
        permalink: true
pages:
  - Kitupiikki: 'index.md'
  - Kirjanpidosta lyhyesti: 'kirjanpito/kirjanpito.md'
  - Asennus: 'asennus.md'
  - Kirjanpidon aloittaminen: 'aloitus/index.md'
  - Määritykset:
    - Perusvalinnat: 'maaritykset/perusvalinnat/index.md'
    - Tilikartta: 'maaritykset/tilikartta/index.md'
    - Tositelajit: 'maaritykset/tositelajit/index.md'
    - Kohdennukset: 'maaritykset/kohdennukset/index.md'
    - Tilinavaus : 'maaritykset/tilinavaus/index.md'
    - Sähköpostin lähettäminen: 'maaritykset/sahkoposti/index.md'
  - Kirjaaminen: 'kirjaus/index.md'
  - Selaaminen ja etsiminen: 'selaus/index.md'
  - Tulosteet: 'tulosteet/index.md'
  - Tilinpäätös: 'tilinpaatos.md'
  - Sähköinen arkisto: 'arkisto.md'
  - Laskutus: 'laskutus.md'
  - Arvonlisävero: 'alv.md'
  - Muita toimintoja: 'muut.md'
  - Lisenssi: 'lisenssi.md'
google_analytics:
  - 'UA-92837430-1'
  - 'auto'
extra_css:
  - 'stylesheets/extra.css'
