site_name: 'Kitupiikin käsikirja'
site_description: 'Avoimen lähdekoodin kirjanpitäjän ohjeet'
site_author: 'Arto Hyvättinen'
site_url: 'https://artoh.github.io/kitupiikki'

repo_name: 'GitHub'
repo_url: 'https://github.com/artoh/kitupiikki'

copyright: 'Copyright &copy; 2017 Arto Hyvättinen GPL3 License'
theme_dir: 'material'
extra:
  logo: 'images/Possu64.png'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  social:
    - type: 'wordpress'
      link: 'https://kitupiikki.wordpress.com'
    - type: 'github'
      link: 'https://github.com/artoh/kitupiikki'
    - type: 'youtube'
      link: 'https://youtube.com/kitupiikki'
markdown_extensions:
  - admonition
  - footnotes
  - meta
pages:
  - Kitupiikki: 'index.md'
  - Asennus: 'asennus.md'
  - Kirjanpidon aloittaminen: 'aloitus.md'
  - Kirjaaminen: 'kirjaus.md'
  - Raportit: 'raportti.md'
  - Tilinpäätös: 'tilinpaatos.md'
  - Arvonlisävero: 'alv.md'
  - Lisenssi: 'lisenssi.md'
google_analystic:
  - 'UA-92837430-1'
  - 'auto'

